Added timeout for blocking calls in RequestTrackingContextValve
magro/memcached-session-manager pull request #412
Opened 2019-10-14 11:35 UTC by mako-fdc

- The `spymemcached` library internally uses a `LinkedBlockingQueue` with a maximum capacity to store operations.
- If this queue is filled up, e.g. due to memcached problems, new adds timeout after a longer time period (currently 10s).
- This internal queue should not be able block the page delivery of the tomcat thread for that long.
Therefore, this commit proposes a timeout on the MSM side to handle this situation.

Here is a corresponding ThreadDump:

```
"http-nio-8443-exec-9" #289 daemon prio=5 os_prio=0 tid=0x00007fb5c02c0800 nid=0xc53 waiting on condition [0x00007fb445336000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006dfe00150> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
        at java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:385)
        at net.spy.memcached.protocol.TCPMemcachedNodeImpl.addOp(TCPMemcachedNodeImpl.java:387)
        at net.spy.memcached.MemcachedConnection.addOperation(MemcachedConnection.java:1285)
        at net.spy.memcached.MemcachedConnection.addOperation(MemcachedConnection.java:1247)
        at net.spy.memcached.MemcachedConnection.enqueueOperation(MemcachedConnection.java:1203)
        at net.spy.memcached.MemcachedClient.asyncGet(MemcachedClient.java:1044)
        at net.spy.memcached.MemcachedClient.get(MemcachedClient.java:1229)
        at de.javakaffee.web.msm.storage.MemcachedStorageClient.get(MemcachedStorageClient.java:62)
        at de.javakaffee.web.msm.MemcachedSessionService$2.get(MemcachedSessionService.java:486)
        at de.javakaffee.web.msm.MemcachedNodesManager$2.isNodeAvailable(MemcachedNodesManager.java:151)
        at de.javakaffee.web.msm.MemcachedNodesManager$2.isNodeAvailable(MemcachedNodesManager.java:146)
        at de.javakaffee.web.msm.NodeAvailabilityCache.updateIsNodeAvailable(NodeAvailabilityCache.java:132)
        at de.javakaffee.web.msm.NodeAvailabilityCache.isNodeAvailable(NodeAvailabilityCache.java:121)
        at de.javakaffee.web.msm.NodeIdService.isNodeAvailable(NodeIdService.java:91)
        at de.javakaffee.web.msm.NodeIdService.getMemcachedNodeId(NodeIdService.java:184)
        at de.javakaffee.web.msm.NodeIdService.getNewNodeIdIfUnavailable(NodeIdService.java:206)
        at de.javakaffee.web.msm.MemcachedNodesManager.getNewSessionIdIfNodeFromSessionIdUnavailable(MemcachedNodesManager.java:505)
        at de.javakaffee.web.msm.MemcachedSessionService.changeSessionIdOnMemcachedFailover(MemcachedSessionService.java:901)
        at de.javakaffee.web.msm.RequestTrackingContextValve.changeRequestedSessionId(RequestTrackingContextValve.java:128)
        at de.javakaffee.web.msm.RequestTrackingContextValve.invoke(RequestTrackingContextValve.java:98)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at de.javakaffee.web.msm.RequestTrackingHostValve.invoke(RequestTrackingHostValve.java:158)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1527)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1484)
        - locked <0x00000006dfddc458> (a org.apache.tomcat.util.net.SecureNioChannel)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```
I'm happy about feedback and an assessment, whether other calls should to `spymemcached` should be wrapped.

2019-10-16 15:23 UTC, magro requested changes
At first thanks for the PR! 

A general remark: It depends on the msm configuration if msm is providing "optional" functionality (session "backup" in case of sticky sessions) or "required" functionality (session "storage" in case of "non-sticky" sessions). So there are installations/configurations out there, where it makes sense to block the user request until the session has been stored in memcached.
I think it's also related to the `sessionBackupAsync` setting: as I understand you, you're probably running with `sessionBackupAsync=true`. For installations with `sessionBackupAsync=false`, I'd say the previous/current behavior should be retained. Would you agree with that?

In this case, the implementation should be changed accordingly.

Regarding the code: because it's closely related to spymemcached, I'd suggest to move the code from `RequestTrackingContextValve` to `MemcachedStorageClient`. Then it's also easier to see, which methods should be "wrapped".

2019-10-16 15:23 UTC, magro commented on core/src/main/java/de/javakaffee/web/msm/TimeoutExecutor.java
> +    static final int DEFAULT_CALLABLE_TIMEOUT_MS = getSystemProperty(CALLABLE_TIMEOUT_MS_KEY, 1500);
I'd prefer to use a default value similar to the timeout of spymemcached (10 seconds?).

Naming: shouldn't it be s.th. like `TIMEOUT_MS` (i.e. not "default")?

2019-10-16 15:23 UTC, magro commented on core/src/main/java/de/javakaffee/web/msm/TimeoutExecutor.java
> +            log.debug("Exception on callable with timeoue (timeoutMs: " + timeoutMs + ").", e);
This should be at least info, if not warn: if this happens more often or regularly, this should be considered an (infrastructure) issue that should be analysed.

Typo: "timeoue"

2019-10-17 15:12 UTC, mako-fdc commented
@magro Thank you for the assessment.

Yes, the problem occurred with a configuration `sessionBackupAsync=true` (default, if missing) and `sticky="true"` in the `context.xml`.

Good point. From my point of view, with` sessionBackupAsync=false` it depends on type of application. For some applications, a fast page delivery may be more important than to have a session. Other applications may not work without a session.

**Option A:** Retain the previous/current behavior for the case `sessionBackupAsync=false`.
**Option B:** We could let the user decide with an additional option:
- forceCircuitBreak=false (default: not applied if sessionBackupAsync=false)
- forceCircuitBreak=true (always applied) 
I'm fine with both versions. Please pick the one that suites the project best. I will implement it.

I agree, the `MemcachedStorageClient` feels like better place. I can wrap all calls there, i.e. `add`, `set`, `get`, `delete` .
You may want to consider a similar implementation for the redis client later.

2019-10-19 01:01 UTC, magro commented
Let's choose option a.

Yes, I've seen the failed travis build, need to fix that.

2019-10-25 12:15 UTC, mako-fdc commented
@margo Thank you for the decision.

I'm trying to include the circuit breaker directly in the `MemcachedStorageClient` now, but I'm not  100% sure which call path to wrap, because sometimes there is already a similar circuit breaker logic in use. 

Cloud you kindly point out the numbers of the calls (see below) we should wrap?

In the `MemcachedStorageClient`  the `add`, `set`, and `delete` methods return a `Future<Boolean>,` which is sometimes used with a timeout, i.e. `future.get(timeout, TimeUnit.MILLISECONDS)`. I created a list of all callers and their eventual timeouts below.

In the `MemcachedStorageClient` the get method directly delivers a `byte[]`, but the get method of the `MemcachedClient` internally uses a  `asyncGet(key, tc).get(this.operationTimeout, TimeUnit.MILLISECONDS)`. Thus, all get calls on the `MemcachedStorageClient` are already "protected" with the `operationTimeout` in the `MemcachedClient`.

Sadly, I don't have a thread dump from our production system to verify which code path blocked us in production. The stacktrace shown in the PR is a reproduction trial.

**`add` calls with timeout:**
```
01. LockingStrategy.OnAfterBackupSessionTask#pingSessionBackup(MBS) using MemcachedSessionService#.getOperationTimeout()
02. LockingStrategy.OnBackupWithoutLoadedSessionTask#pingSessionBackup(S) using 200
```

**`add` calls without timeout:**
```
03. LockingStrategy#acquireLock(S,l,l,l) no timeout = waits for completion
04. LockingStrategy#pingSession(S) no timeout = waits for completion
05. LockingStrategy#pingSession(MBS,BSS) no timeout = waits for completion
```

**`set` calls with timeout:**
```
06. BackupSessionTask#storeSessionInMemcached(MBS,b[]) using MemcachedSessionService#getSessionBackupTimeout()
07. LockingStrategy#storeSessionInMeonBackupWithoutLoadedSession(S,S,BSS) using MemcachedSessionService#getSessionBackupTimeout()
08. LockingStrategy#onAfterBackupSession(MBS,b,F<BR>,S,BSS) using MemcachedSessionService#getSessionBackupTimeout()
```

**`set` calls without timeout:**
```
09. LockingStrategy.OnAfterBackupSessionTask#saveSessionBackupFromResult(BR) ignores return value of set()
10. LockingStrategy.OnAfterBackupSessionTask#saveValidityBackup() ignores return value of set()
11. LockingStrategy.OnBackupWithoutLoadedSessionTask#call() ignores return value of set()
12. LockingStrategy.OnAfterBackupSessionTask#saveSessionBackup(MBS,S) no timeout = waits for completion
```

**`delete` calls with timeout:**
`None`

**`delete` calls without timeout:**
```
13. BackupSessionService#releaseLock(MBS) ignores return value of delete()
14. BackupSessionTask#releaseLock() ignores return value of delete()
15. LockingStrategy#onAfterDeleteFromMemcached(S) ignores return value of delete()
16. MemcachedSessionService#deleteFromMemcached(S) ignores return value of delete()
17. MemcachedSessionService#loadFromMemcached(S) ignores return value of delete()
18. LockingStrategy#releaseLock(S) no timeout = waits for completion
```

All timeouts are in MS. 
The default value for the `sessionBackupTimeout` is `100`. It can be set in the `context.xml`.

2021-06-11 07:57 UTC, mako-fdc commented
Closed: Not needed anymore.

2021-06-11 07:57 UTC, closed without merging